# Generated by Django 5.2.7 on 2025-10-21 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
