# Generated by Django 5.2.7 on 2025-10-23 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolot', '0003_car_owner_profile_avatar_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, default='Used', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN'),
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified')], default='new', max_length=12)),
                ('interested_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='autolot.car')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
