# Generated by Django 5.2.7 on 2025-10-23 00:37
from django.db import migrations, models


def fill_missing_vins_and_mileage(apps, schema_editor):
    Car = apps.get_model('autolot', 'Car')

    for car in Car.objects.filter(vin__isnull=True):
        car.vin = f"TEMP{car.pk:013d}"[:17]
        if car.mileage is None:
            car.mileage = 0
        car.save(update_fields=['vin', 'mileage'])

    for car in Car.objects.filter(mileage__isnull=True):
        car.mileage = 0
        car.save(update_fields=['mileage'])

class Migration(migrations.Migration):

    dependencies = [
        ('autolot', '0004_alter_car_condition_alter_car_make_alter_car_model_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_missing_vins_and_mileage, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='VIN'),
        ),
    ]
