# Generated by Django 4.2.25 on 2025-11-13 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolot', '0006_alter_car_make_alter_car_model_alter_car_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cash_down',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
