# Generated by Django 4.2.25 on 2025-11-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autolot', '0007_car_cash_down_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
